export const signs = [
  { name: 'Aries', sanskritName: 'Mesha', element: 'Fire', icon: '♈︎', date: 'Mar 21 - Apr 19', symbol: 'Ram', traits: ['Courageous', 'Determined', 'Confident', 'Enthusiastic'], description: 'As the first sign of the zodiac, Aries is always the first to start anything. They are pioneers and leaders, known for their fiery energy and passion.', color: '#ef4444' },
  { name: 'Taurus', sanskritName: 'Vrishabha', element: 'Earth', icon: '♉︎', date: 'Apr 20 - May 20', symbol: 'Bull', traits: ['Reliable', 'Patient', 'Practical', 'Devoted'], description: 'Taurus is an earth sign, represented by the bull. Like their celestial spirit animal, Taureans enjoy relaxing in serene, bucolic environments.', color: '#10b981' },
  { name: 'Gemini', sanskritName: 'Mithuna', element: 'Air', icon: '♊︎', date: 'May 21 - Jun 20', symbol: 'Twins', traits: ['Adaptable', 'Outgoing', 'Intelligent', 'Curious'], description: 'Gemini is the sign of the twins. They are social butterflies, known for their wit and ability to adapt to any situation with ease.', color: '#3b82f6' },
  { name: 'Cancer', sanskritName: 'Karkata', element: 'Water', icon: '♋︎', date: 'Jun 21 - Jul 22', symbol: 'Crab', traits: ['Tenacious', 'Highly Imaginative', 'Loyal', 'Emotional'], description: 'Cancer is a cardinal water sign. Represented by the crab, this oceanic crustacean seamlessly weaves between the sea and shore.', color: '#6366f1' },
  { name: 'Leo', sanskritName: 'Simha', element: 'Fire', icon: '♌︎', date: 'Jul 23 - Aug 22', symbol: 'Lion', traits: ['Creative', 'Passionate', 'Generous', 'Warm-hearted'], description: 'Leo is the lion of the zodiac. They are natural leaders, confident and bright, often the center of attention in any room.', color: '#f59e0b' },
  { name: 'Virgo', sanskritName: 'Kanya', element: 'Earth', icon: '♍︎', date: 'Aug 23 - Sep 22', symbol: 'Virgin', traits: ['Loyal', 'Analytical', 'Kind', 'Hard-working'], description: 'Virgo is an earth sign historically represented by the goddess of wheat and agriculture, an association that speaks to Virgo\'s deep-rooted presence in the material world.', color: '#059669' },
  { name: 'Libra', sanskritName: 'Tula', element: 'Air', icon: '♎︎', date: 'Sep 23 - Oct 22', symbol: 'Scales', traits: ['Cooperative', 'Diplomatic', 'Gracious', 'Fair-minded'], description: 'Libra is an air sign represented by the scales, reflecting Libra\'s fixation on balance and harmony.', color: '#ec4899' },
  { name: 'Scorpio', sanskritName: 'Vrishchika', element: 'Water', icon: '♏︎', date: 'Oct 23 - Nov 21', symbol: 'Scorpion', traits: ['Resourceful', 'Brave', 'Passionate', 'A true friend'], description: 'Scorpio is a water sign that uses emotional energy as fuel, cultivating powerful wisdom through both the physical and unseen realms.', color: '#7c3aed' },
  { name: 'Sagittarius', sanskritName: 'Dhanu', element: 'Fire', icon: '♐︎', date: 'Nov 22 - Dec 21', symbol: 'Archer', traits: ['Generous', 'Idealistic', 'Great sense of humor'], description: 'Represented by the archer, Sagittarians are always on a quest for knowledge. They love to travel and explore the unknown.', color: '#f43f5e' },
  { name: 'Capricorn', sanskritName: 'Makara', element: 'Earth', icon: '♑︎', date: 'Dec 22 - Jan 19', symbol: 'Goat', traits: ['Responsible', 'Disciplined', 'Self-control', 'Good managers'], description: 'The last earth sign of the zodiac, Capricorn is represented by the sea-goat, a mythological creature with the body of a goat and the tail of a fish.', color: '#475569' },
  { name: 'Aquarius', sanskritName: 'Kumbha', element: 'Air', icon: '♒︎', date: 'Jan 20 - Feb 18', symbol: 'Water Bearer', traits: ['Progressive', 'Original', 'Independent', 'Humanitarian'], description: 'Despite the "aqua" in its name, Aquarius is actually the last air sign of the zodiac. They are intellectuals who value community and progress.', color: '#06b6d4' },
  { name: 'Pisces', sanskritName: 'Meena', element: 'Water', icon: '♓︎', date: 'Feb 19 - Mar 20', symbol: 'Fish', traits: ['Compassionate', 'Artistic', 'Intuitive', 'Gentle', 'Wise'], description: 'Pisces, a water sign, is the last constellation of the zodiac. It\'s symbolized by two fish swimming in opposite directions, representing the constant division of Pisces\'s attention between fantasy and reality.', color: '#8b5cf6' },
];

export const zodiacHeader = {
  title: 'Explore the Zodiac',
  subtitle: 'Choose your sign to reveal your celestial profile'
};
